default_platform(:ios)

platform :ios do
  desc "Build .ipa"
  lane :build do
    gym(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store"
    )
  end

  desc "Upload to TestFlight"
  lane :beta do
    build
    pilot(
      skip_waiting_for_build_processing: true
    )
  end
end
