# Follows client_app lints with a few additions
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    avoid_print: true
    always_use_package_imports: true
    directives_ordering: true
    prefer_final_locals: true
