// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbryznobkmhnmrjnbcln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicnl6bm9ia21obm1yam5iY2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjE5NDksImV4cCI6MjA3MzUzNzk0OX0.wMPR5sgIROLZg_tz04rq_PdJYiV_XG-zGERFVffuCz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});