name: Client App CI (React Native)

on:
  push:
    branches: [ main, develop, "cursor/**" ]
    paths:
      - 'apps/client_app/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/client_app/**'

jobs:
  android-build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: apps/client_app
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: apps/client_app/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses
      - name: Build Android Debug APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew clean assembleDebug --no-daemon
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: client-app-apk
          path: apps/client_app/android/app/build/outputs/apk/debug/*.apk

  ios-build:
    runs-on: macos-14
    defaults:
      run:
        working-directory: apps/client_app
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: apps/client_app/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Ruby and CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false
      - run: sudo gem install cocoapods
      - name: Install iOS pods
        working-directory: apps/client_app/ios
        run: pod install --repo-update
      - name: Build iOS (Simulator)
        working-directory: apps/client_app/ios
        run: |
          xcodebuild -workspace RNTempGen.xcworkspace \
            -scheme RNTempGen \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' build
